---
- name: Check client exists
  ansible.builtin.shell: |
    docker exec keycloak /opt/keycloak/bin/kcadm.sh get clients \
      -r {{ keycloak_realm }} \
      -q clientId={{ keycloak_client.client_id }}
  register: client_check
  failed_when: false
  changed_when: false

- name: Create client if not exists
  ansible.builtin.shell: |
    docker exec keycloak /opt/keycloak/bin/kcadm.sh create clients \
      -r {{ keycloak_realm }} \
      -s clientId={{ keycloak_client.client_id }} \
      -s enabled=true \
      -s clientAuthenticatorType=client-secret \
      -s secret={{ keycloak_client.client_secret }} \
      -s 'redirectUris={{ keycloak_client.redirect_uris | to_json }}' \
      -s 'attributes={"post.logout.redirect.uris":"keycloak_client.post_logout_redirect_uris", "backchannel.logout.session.required": "keycloak_client.backchannel_logout_session_required", "backchannel.logout.url": "keycloak_client.backchannel_logout_url"}' \
      -i
  when: client_check.stdout == "[ ]"
