---
- name: Start keycloak postgres container
  community.docker.docker_container:
    name: keycloak_postgres
    image: postgres:18.3
    state: healthy
    restart_policy: unless-stopped
    networks:
      - name: private
    exposed_ports:
      - 5432
    env:
      POSTGRES_USER: "{{ vault_keycloak_db_username }}"
      POSTGRES_PASSWORD: "{{ vault_keycloak_db_password }}"
      POSTGRES_DB: "{{ vault_keycloak_db_database_name }}"
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
