---
- import_tasks: database.yml

- name: Create keycloak docker context dir
  ansible.builtin.file:
    path: "{{ keycloak_build_context }}"
    state: directory

- name: Copy keycloak/Dockerfile
  ansible.builtin.copy:
    src: Dockerfile
    dest: "{{ keycloak_build_context }}/Dockerfile"

- name: Build keycloak image
  community.docker.docker_image_build:
    name: "{{ keycloak_image }}"
    path: "{{ keycloak_build_context }}"

- name: Start keycloak container
  community.docker.docker_container:
    name: keycloak
    image: "{{ keycloak_image }}"
    command: start --optimized
    state: healthy
    restart_policy: unless-stopped
    networks:
      - name: public
      - name: private
    exposed_ports:
      - 8080
    env:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "{{ vault_keycloak_admin_password }}"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: "https://auth.{{ domain_name }}"
      KC_PROXY_HEADERS: "xforwarded"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://db:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "{{ vault_keycloak_db_password }}"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      VIRTUAL_HOST: "auth.{{ domain_name }}"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "auth.{{ domain_name }}"
    healthcheck:
      test: [ "CMD-SHELL", "bash -c \"exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && grep 200 <&3\"" ]
      interval: 10s
      timeout: 5s
      retries: 3

- name: Login kcadm
  ansible.builtin.shell: |
    docker exec keycloak /opt/keycloak/bin/kcadm.sh config credentials \
      --server http://localhost:8080 \
      --realm master \
      --user admin \
      --password {{ vault_keycloak_admin_password }}
  changed_when: false

- name: Check realm exists
  ansible.builtin.shell: |
    docker exec keycloak /opt/keycloak/bin/kcadm.sh get realms/{{ keycloak_realm }}
  register: realm_check
  failed_when: false
  changed_when: false

- name: Create realm if not exists
  ansible.builtin.shell: |
    docker exec keycloak /opt/keycloak/bin/kcadm.sh create realms \
      -s realm={{ keycloak_realm }} \
      -s enabled=true
  when: realm_check.rc != 0

- name: Create keycloak clients
  ansible.builtin.include_tasks: clients.yml
  loop: "{{ keycloak_clients }}"
  loop_control:
    loop_var: keycloak_client
    label: "{{ keycloak_client.client_id }}"
