---
keycloak_realm: untitled-bff
keycloak_issuer_uri: "https://auth.{{ domain_name }}/realms/{{ keycloak_realm }}"
keycloak_build_context: "/home/{{ ansible_user }}/keycloak"
keycloak_image: untitled/keycloak:latest

keycloak_clients:
  - client_id: untitled-bff-client
    client_secret: "{{ vault_keycloak_client_01_secret }}"
    root_url: ""
    base_url: ""
    home_url: ""
    redirect_uris:
      - "https://bff.{{ domain_name }}/login/oauth2/code/untitled-bff"
    post_logout_redirect_uris: "https://spotfuckingify.com/*"
    backchannel_logout_session_required: true
    backchannel_logout_url: "https://bff.{{ domain_name }}/logout/connect/back-channel/untitled-bff"
  - client_id: immich-client
    client_secret: "{{ vault_keycloak_client_02_secret }}"
    root_url: ""
    base_url: ""
    home_url: ""
    redirect_uris:
      - "app.immich:///oauth-callback"
      - "https://immich.spotfuckingify.com/auth/login"
      - "https://immich.spotfuckingify.com/user-settings"
    post_logout_redirect_uris: "+"
    backchannel_logout_session_required: false
    backchannel_logout_url: ""
