---
- name: Start postgres container
  community.docker.docker_container:
    name: db
    image: postgres:18.3
    state: healthy
    restart_policy: unless-stopped
    networks:
      - name: private
    exposed_ports:
      - 5432
    env:
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "{{ vault.db_password }}"
      POSTGRES_DB: "keycloak"
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
