---
- name: Create public network
  community.docker.docker_network:
    name: public
    driver: bridge

- name: Create private network
  community.docker.docker_network:
    name: private
    driver: bridge
    internal: true

- name: Start nginx-proxy container
  community.docker.docker_container:
    name: nginx-proxy
    image: nginxproxy/nginx-proxy:1.10
    restart_policy: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - name: public
      - name: private
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

- name: Start acme-companion container
  community.docker.docker_container:
    name: acme-companion
    image: nginxproxy/acme-companion:2.6
    restart_policy: unless-stopped
    networks:
      - name: public
      - name: private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

- name: Start nguyen-sp container
  community.docker.docker_container:
    name: nguyen-sp
    image: ghcr.io/nguyennt1103/nguyen-sp:latest
    restart_policy: unless-stopped
    networks:
      - name: private
    exposed_ports:
      - 80
    env:
      - VIRTUAL_HOST: sp.spotfuckingify.com
      - LETSENCRYPT_HOST: sp.spotfuckingify.com
